version: '3'

services:
  app:
    build: '.'
    ports:
      - '4567:4567'
    environment:
      - HOGE: hogeValue
    # https://docs.docker.com/config/containers/logging/awslogs/
    logging:
      driver: 'awslogs'
      options:
        awslogs-region: 'ap-northeast-1'
        awslogs-group: 'docker'
        tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}-{{.ID}}'
        awslogs-create-group: 'true'
        awslogs-datetime-format: '\[%Y-%m-%d %H:%M:%S\]'
